### ISSUE TITLE
Multiple soundplayer (maybe with some application crashs)

### ISSUE THREAD

**Issue by robinmanuelthiel** [Thepagedot/IRMGARD#3]
The app crashes with an `OutOfMemoryException` after some soundfiles have been played.

**Comment by MarcelWi-tpd** [comment]
I'm not so sure if the MediaPlayer crash the application. I just see OutOfMemoryException only for Bitmap images. 

https://github.com/Thepagedot/IRMGARD/issues/5

Apart from this I fixed the bug that multiple sound files can be played at the same time because of multiple media players. The class now has only one media player which will be stopped and released before the next file should be played. Comes with the next commit.

**Comment by MarcelWi-tpd** [comment]
Done. a584ab0685f359319ce0bf311f08e9e5ca78de64
